// Define study
const study = lab.util.fromObject({
  "title": "root",
  "type": "lab.flow.Sequence",
  "parameters": {},
  "plugins": [
    {
      "type": "lab.plugins.Metadata"
    },
    {
      "type": "lab.plugins.PostMessage"
    }
  ],
  "metadata": {
    "title": "",
    "description": "",
    "repository": "",
    "contributors": ""
  },
  "files": {},
  "responses": {},
  "content": [
    {
      "type": "lab.flow.Sequence",
      "files": {},
      "parameters": {},
      "responses": {},
      "messageHandlers": {},
      "title": "Brightness Test",
      "shuffle": false,
      "content": [
        {
          "type": "lab.flow.Sequence",
          "files": {},
          "parameters": {},
          "responses": {},
          "messageHandlers": {},
          "title": "Block 100%",
          "content": [
            {
              "type": "lab.canvas.Screen",
              "files": {},
              "parameters": {},
              "messageHandlers": {},
              "viewport": [
                800,
                600
              ],
              "title": "Directions 100%",
              "responses": {
                "keypress(Space)": "continue"
              },
              "content": [
                {
                  "type": "i-text",
                  "version": "2.7.0",
                  "originX": "center",
                  "originY": "center",
                  "left": 0,
                  "top": -25,
                  "width": 351.6,
                  "height": 28.25,
                  "fill": "black",
                  "stroke": null,
                  "strokeWidth": 1,
                  "strokeDashArray": null,
                  "strokeLineCap": "butt",
                  "strokeDashOffset": 0,
                  "strokeLineJoin": "round",
                  "strokeMiterLimit": 4,
                  "scaleX": 1,
                  "scaleY": 1,
                  "angle": 0,
                  "flipX": false,
                  "flipY": false,
                  "opacity": 1,
                  "shadow": null,
                  "visible": true,
                  "clipTo": null,
                  "backgroundColor": "",
                  "fillRule": "nonzero",
                  "paintFirst": "fill",
                  "globalCompositeOperation": "source-over",
                  "transformMatrix": null,
                  "skewX": 0,
                  "skewY": 0,
                  "text": "Press the space bar to continue",
                  "fontSize": "25",
                  "fontWeight": "normal",
                  "fontFamily": "sans-serif",
                  "fontStyle": "normal",
                  "lineHeight": 1.16,
                  "underline": false,
                  "overline": false,
                  "linethrough": false,
                  "textAlign": "center",
                  "textBackgroundColor": "",
                  "charSpacing": 0,
                  "id": "34",
                  "styles": {}
                },
                {
                  "type": "i-text",
                  "version": "2.7.0",
                  "originX": "center",
                  "originY": "center",
                  "left": -12,
                  "top": -85,
                  "width": 594.39,
                  "height": 45.2,
                  "fill": "black",
                  "stroke": null,
                  "strokeWidth": 1,
                  "strokeDashArray": null,
                  "strokeLineCap": "butt",
                  "strokeDashOffset": 0,
                  "strokeLineJoin": "round",
                  "strokeMiterLimit": 4,
                  "scaleX": 1,
                  "scaleY": 1,
                  "angle": 0,
                  "flipX": false,
                  "flipY": false,
                  "opacity": 1,
                  "shadow": null,
                  "visible": true,
                  "clipTo": null,
                  "backgroundColor": "",
                  "fillRule": "nonzero",
                  "paintFirst": "fill",
                  "globalCompositeOperation": "source-over",
                  "transformMatrix": null,
                  "skewX": 0,
                  "skewY": 0,
                  "text": "Please set your brightness to 100%",
                  "fontSize": "40",
                  "fontWeight": "bold",
                  "fontFamily": "Times New Roman",
                  "fontStyle": "normal",
                  "lineHeight": 1.16,
                  "underline": false,
                  "overline": false,
                  "linethrough": false,
                  "textAlign": "center",
                  "textBackgroundColor": "",
                  "charSpacing": 0,
                  "id": "31",
                  "styles": {}
                }
              ]
            },
            {
              "type": "lab.flow.Loop",
              "files": {},
              "parameters": {},
              "messageHandlers": {},
              "title": "Trial",
              "templateParameters": [
                {
                  "image": "Square.png",
                  "r": "s"
                },
                {
                  "image": "Circle.png",
                  "r": "c"
                },
                {
                  "image": "Triangle.png",
                  "r": "t"
                }
              ],
              "responses": {},
              "sample": {
                "mode": "draw-replace",
                "n": "20"
              },
              "shuffleGroups": [],
              "template": {
                "type": "lab.flow.Sequence",
                "files": {},
                "parameters": {},
                "responses": {},
                "messageHandlers": {},
                "title": "Sequence",
                "content": [
                  {
                    "type": "lab.canvas.Screen",
                    "parameters": {},
                    "messageHandlers": {},
                    "viewport": [
                      800,
                      600
                    ],
                    "title": "Stim",
                    "files": {
                      "Square.png": "embedded\u002F74e1c53e34a77c132cdbcce3dd0d15d7562f94dcb11df2af8d92f46dbe2a3d29.png",
                      "Triangle.png": "embedded\u002F2175a748b69f67d1d02065c847110834e3036e299471eac33a55d41826761cf0.png",
                      "Circle.png": "embedded\u002F401eaa24a0e933f3edc3793fb742f944c4a99a607702c4d9ecff5ab24b0c838f.png"
                    },
                    "content": [
                      {
                        "type": "i-text",
                        "version": "2.7.0",
                        "originX": "center",
                        "originY": "center",
                        "left": 0,
                        "top": -250,
                        "width": 295.25,
                        "height": 36.16,
                        "fill": "black",
                        "stroke": null,
                        "strokeWidth": 1,
                        "strokeDashArray": null,
                        "strokeLineCap": "butt",
                        "strokeDashOffset": 0,
                        "strokeLineJoin": "round",
                        "strokeMiterLimit": 4,
                        "scaleX": 1,
                        "scaleY": 1,
                        "angle": 0,
                        "flipX": false,
                        "flipY": false,
                        "opacity": 1,
                        "shadow": null,
                        "visible": true,
                        "clipTo": null,
                        "backgroundColor": "",
                        "fillRule": "nonzero",
                        "paintFirst": "fill",
                        "globalCompositeOperation": "source-over",
                        "transformMatrix": null,
                        "skewX": 0,
                        "skewY": 0,
                        "text": "What Shape is This?",
                        "fontSize": 32,
                        "fontWeight": "normal",
                        "fontFamily": "sans-serif",
                        "fontStyle": "normal",
                        "lineHeight": 1.16,
                        "underline": false,
                        "overline": false,
                        "linethrough": false,
                        "textAlign": "center",
                        "textBackgroundColor": "",
                        "charSpacing": 0,
                        "id": "4",
                        "styles": {}
                      },
                      {
                        "type": "i-text",
                        "version": "2.7.0",
                        "originX": "center",
                        "originY": "center",
                        "left": 15,
                        "top": -200,
                        "width": 534.36,
                        "height": 28.25,
                        "fill": "black",
                        "stroke": null,
                        "strokeWidth": 1,
                        "strokeDashArray": null,
                        "strokeLineCap": "butt",
                        "strokeDashOffset": 0,
                        "strokeLineJoin": "round",
                        "strokeMiterLimit": 4,
                        "scaleX": 1,
                        "scaleY": 1,
                        "angle": 0,
                        "flipX": false,
                        "flipY": false,
                        "opacity": 1,
                        "shadow": null,
                        "visible": true,
                        "clipTo": null,
                        "backgroundColor": "",
                        "fillRule": "nonzero",
                        "paintFirst": "fill",
                        "globalCompositeOperation": "source-over",
                        "transformMatrix": null,
                        "skewX": 0,
                        "skewY": 0,
                        "text": "Press 's' for square, 't' for triangle, or 'c' for circle",
                        "fontSize": "25",
                        "fontWeight": "normal",
                        "fontFamily": "sans-serif",
                        "fontStyle": "normal",
                        "lineHeight": 1.16,
                        "underline": false,
                        "overline": false,
                        "linethrough": false,
                        "textAlign": "center",
                        "textBackgroundColor": "",
                        "charSpacing": 0,
                        "id": "44",
                        "styles": {}
                      },
                      {
                        "type": "image",
                        "version": "2.7.0",
                        "originX": "center",
                        "originY": "center",
                        "left": 0,
                        "top": 75,
                        "width": 803.0400000000001,
                        "height": 452.48,
                        "fill": "black",
                        "stroke": null,
                        "strokeWidth": 0,
                        "strokeDashArray": null,
                        "strokeLineCap": "butt",
                        "strokeDashOffset": 0,
                        "strokeLineJoin": "round",
                        "strokeMiterLimit": 4,
                        "scaleX": 0.28,
                        "scaleY": 0.28,
                        "angle": 0,
                        "flipX": false,
                        "flipY": false,
                        "opacity": 1,
                        "shadow": null,
                        "visible": true,
                        "clipTo": null,
                        "backgroundColor": "",
                        "fillRule": "nonzero",
                        "paintFirst": "fill",
                        "globalCompositeOperation": "source-over",
                        "transformMatrix": null,
                        "skewX": 0,
                        "skewY": 0,
                        "crossOrigin": "",
                        "cropX": 0,
                        "cropY": 0,
                        "id": "90",
                        "src": "${ this.files[this.parameters.image] }",
                        "filters": [],
                        "naturalWidth": 2868,
                        "naturalHeight": 1616,
                        "autoScale": "height"
                      }
                    ],
                    "correctResponse": "${parameters.r}",
                    "responses": {
                      "keypress(s)": "s",
                      "keypress(t)": "t",
                      "keypress(c)": "c"
                    },
                    "tardy": false
                  },
                  {
                    "type": "lab.canvas.Screen",
                    "content": [],
                    "files": {},
                    "parameters": {},
                    "responses": {},
                    "messageHandlers": {},
                    "viewport": [
                      800,
                      600
                    ],
                    "title": "Inter-stim",
                    "timeout": "200"
                  }
                ]
              }
            }
          ]
        }
      ]
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "version": "2.7.0",
          "originX": "center",
          "originY": "center",
          "left": 0,
          "top": 0,
          "width": 465.83,
          "height": 120.05,
          "fill": "black",
          "stroke": null,
          "strokeWidth": 1,
          "strokeDashArray": null,
          "strokeLineCap": "butt",
          "strokeDashOffset": 0,
          "strokeLineJoin": "round",
          "strokeMiterLimit": 4,
          "scaleX": 1,
          "scaleY": 1,
          "angle": 0,
          "flipX": false,
          "flipY": false,
          "opacity": 1,
          "shadow": null,
          "visible": true,
          "clipTo": null,
          "backgroundColor": "",
          "fillRule": "nonzero",
          "paintFirst": "fill",
          "globalCompositeOperation": "source-over",
          "transformMatrix": null,
          "skewX": 0,
          "skewY": 0,
          "text": "Thank you for your participation!\n\nPress any key to finish.",
          "fontSize": 32,
          "fontWeight": "bold",
          "fontFamily": "serif",
          "fontStyle": "normal",
          "lineHeight": 1.16,
          "underline": false,
          "overline": false,
          "linethrough": false,
          "textAlign": "center",
          "textBackgroundColor": "",
          "charSpacing": 0,
          "id": "323",
          "styles": {}
        }
      ],
      "files": {},
      "parameters": {},
      "responses": {
        "keypress": "a"
      },
      "messageHandlers": {},
      "viewport": [
        800,
        600
      ],
      "title": "Screen"
    }
  ]
})

// Let's go!
study.run()